[packages.semanifold-resolver]
path = "crates/resolver"

[packages.semanifold]
path = "crates/semanifold"

[tags]
chore = "Chore"
feat = "New Feature"
fix = "Bug Fix"
refactor = "Refactor"
perf = "Performance Improvement"
