[tags]
feat = "New Feature"
fix = "Bug Fix"
chore = "Chore"
refactor = "Refactor"
perf = "Performance Improvement"

[packages]
semanifold = { path = "crates/semanifold" }
semanifold-resolver = { path = "crates/resolver" }
