[packages]
semanifold-resolver = { path = "crates/resolver" }
semanifold = { path = "crates/semanifold" }

[tags]
chore = "Chore"
feat = "New Feature"
fix = "Bug Fix"
perf = "Performance Improvement"
refactor = "Refactor"
